version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    container_name: web
    restart: always
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - node-network

  bot-discord:
    build:
      context: ./bot-discord
      dockerfile: Dockerfile
    environment:
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    container_name: bot-discord
    restart: always
    volumes:
      - ./bot-discord:/usr/src/bot
    ports:
      - "3030:3030"
    depends_on:
      - web
    networks:
      - node-network

  apollo-server:
    build:
      context: ./apollo-server
      dockerfile: Dockerfile
    container_name: apollo-server
    volumes:
      - ./apollo-server:/app
    ports:
      - "7070:7070"
    depends_on:
      - web
    networks:
      - node-network

  #bdd
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge