import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'La zone | VALORANT',
  description: 'Generated by create next app',
}
 
export default function ValorantLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      {children}
  )
}