import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'La zone | VALORANT',
  description: 'Generated by create next app',
}

export default function ValorantLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div className={"container mx-auto p-4"}>
    {children}
  </div>
}